    CREATE TABLE T_UNV_ALUNO (
        ID_ALUNO INT PRIMARY KEY, 
        NM_ALUNO VARCHAR2(100) NOT NULL, 
        DT_NASCIMENTO DATE,
        CPF NUMBER(11) NOT NULL,
        SEXO CHAR(1) CHECK(SEXO='M' OR SEXO='F' OR SEXO='I')
    );

    CREATE TABLE T_UNV_CURSO(
        ID_CURSO INT PRIMARY KEY,
        NM_CURSO VARCHAR2(100) NOT NULL   
    );

    CREATE TABLE T_UNV_PROFESSOR(
        ID_PROFESSOR INT PRIMARY KEY,
        NM_PROFESSOR VARCHAR2(100) NOT NULL
    );

    CREATE TABLE T_UNV_DICIPLINA(
        ID_DICIPLINA INT PRIMARY KEY,
        NM_DICIPLINA VARCHAR2(155) NOT NULL,
        EMENTA VARCHAR2(155),
        REF_BIBLIOGRAFICA VARCHAR2(155) NOT NULL,
        METODOLOGIA VARCHAR2(155) NOT NULL,
        CARGA_HORARIA INT CHECK(CARGA_HORARIA > 0 AND CARGA_HORARIA < 200),
        MODALIDADE VARCHAR2(1) CHECK(MODALIDADE IN('P', 'R')),
        ID_CURSO_FK INT REFERENCES T_UNV_CURSO(ID_CURSO)      
    );
    
    CREATE TABLE T_UNV_PROFESSOR_DICIPLINA(
        ID_PROFESSOR_FK INT REFERENCES T_UNV_PROFESSOR(ID_PROFESSOR),
        ID_DICIPLINA_FK INT REFERENCES T_UVN_DICIPLINA(ID_DICIPLINA),
        ID_PROFESSOR_DICIPLINA INT PRIMARY KEY
        
    );