

--  LOCADURA

-- 1 MARCA PODE TER N MODELOS
-- SEQUECE (OU SEQUENCIA)
-- CONTADORES AUTOMÁTICOS

CREATE SEQUENCE SEQ_MARCA;
CREATE SEQUENCE SEQ_MODELO;

-- NEXTVAL-- PRÓXIMO VALOR
-- CURRVAL: É O VALOR ATUAL


-- DEFAUL É A DEFINIÇÃO DE UM VALOR PADRÃO A SER INSERIDO - CASO NÃO SEJA MENCIONADO NO INSERT
CREATE TABLE MARCA (
    ID_MARCA INT DEFAULT SEQ_MARCA.NEXTVAL PRIMARY KEY,
    DS_MARCA VARCHAR(100) NOT NULL
);

CREATE TABLE MODELO(
    ID_MODELO INT DEFAULT SEQ_MODELO.NEXTVAL PRIMARY KEY,
    DS_MODELO VARCHAR(100) NOT NULL,
    COR VARCHAR(30),
    ANO DATE,
    CAMBIO VARCHAR(10) CHECK (CAMBIO IN('AUT', 'MANUAL', 'SEMI-AUT')),
    CATEGORIA VARCHAR(10) CHECK(CATEGORIA IN('HATCH', 'SEDAN', 'SUV')),
    ID_MARCA INT REFERENCES MARCA(ID_MARCA)
);

INSERT INTO MARCA (DS_MARCA) VALUES ('FIAT');

INSERT INTO MARCA (DS_MARCA) VALUES ('FORD');

INSERT INTO MARCA (DS_MARCA) VALUES ('JEEP');

SELECT * FROM MARCA;

SELECT * FROM MODELO;

INSERT INTO MODELO(DS_MODELO, COR, ANO, CAMBIO, CATEGORIA, ID_MARCA)
            VALUES('UNO', 'VERDE', TO_DATE('2010', 'YYYY'), 'MANUAL', 'HATCH', 1);
            
INSERT  INTO MODELO(DS_MODELO, COR, ANO, CAMBIO, CATEGORIA, ID_MARCA)
            VALUES('SIENA', 'VERMELHO', TO_DATE('2015', 'YYYY'), 'AUT', 'SEDAN', 2);
            
INSERT  INTO MODELO(DS_MODELO, COR, ANO, CAMBIO, CATEGORIA, ID_MARCA)
            VALUES('KA', 'PRETO', TO_DATE('2020', 'YYYY'), 'MANUAL', 'HATCH', 3);
            
UPDATE MODELO SET ID_MARCA=4 WHERE ID_MODELO=10 OR ID_MODELO=11;


-- CRROS JOIN
-- NÃO ESTÁ REALIZANDO JUNÇÃO, APENAS CRUZAMENTOS DOS DADOS
SELECT * FROM MARCA, MODELO;

-- EQUI JOIN
SELECT * FROM MARCA, MODELO WHERE MARCA.ID_MARCA = MODELO.ID_MARCA;

-- ALIAS (OU APELIDO)
SELECT * FROM MARCA MA, MODELO MD WHERE MA.ID_MARCA = MD.ID_MARCA;
